/**
 * Revenue-cycle seed. Five completed encounters wait in charge review (four with a
 * scrubber edit, one clean) and four claims sit in the denial work queue.
 * Three CO-16 denials share a root cause: Dr. Patel's lab order favorites carry no
 * diagnosis association, so lab lines drop to the claim without a pointer.
 */
import type { Claim } from "../types";

const created = (at: string) => [{ at, change: "Charges dropped from the encounter" }];

export const claims: Claim[] = [
  {
    id: "CLM-26-0412",
    patientId: "PT-003",
    dos: "2026-09-14",
    provider: "Dr. Ravi Patel",
    department: "Family Medicine",
    insurerId: "INS-MMC",
    payer: "NY Medicaid Managed Care (teaching plan)",
    memberId: "MMC-48284",
    diagnoses: [
      { code: "I10", display: "Essential (primary) hypertension" },
      { code: "E11.9", display: "Type 2 diabetes mellitus without complications" },
    ],
    lines: [
      { line: 1, cpt: "99214", description: "Office visit, established patient, moderate MDM", modifiers: [], dxPointers: ["I10", "E11.9"], units: 1, charge: 260 },
      { line: 2, cpt: "83036", description: "Hemoglobin A1c", modifiers: [], dxPointers: [], units: 1, charge: 42, orderingProvider: "Dr. Ravi Patel" },
      { line: 3, cpt: "82043", description: "Urine albumin, quantitative", modifiers: [], dxPointers: ["E11.9"], units: 1, charge: 28, orderingProvider: "Dr. Ravi Patel" },
      { line: 4, cpt: "36415", description: "Venipuncture", modifiers: [], dxPointers: ["E11.9"], units: 1, charge: 12 },
    ],
    eligibility: "Active",
    requiresReferral: false,
    status: "Charge review",
    history: created("2026-09-15T06:00:00-04:00"),
  },
  {
    id: "CLM-26-0415",
    patientId: "PT-011",
    dos: "2026-09-15",
    provider: "Sam Brooks, NP",
    department: "Internal Medicine",
    insurerId: "INS-CPPO",
    payer: "Crescent Commercial PPO (fictional)",
    memberId: "CPPO-48580",
    diagnoses: [
      { code: "H61.21", display: "Impacted cerumen, right ear" },
      { code: "R03.0", display: "Elevated blood-pressure reading, without diagnosis of hypertension" },
    ],
    lines: [
      { line: 1, cpt: "99213", description: "Office visit, established patient, low MDM", modifiers: ["25"], dxPointers: ["R03.0"], units: 1, charge: 185 },
      { line: 2, cpt: "69210", description: "Removal of impacted cerumen with instrumentation, unilateral", modifiers: ["RT"], dxPointers: ["H61.21"], units: 1, charge: 95 },
    ],
    eligibility: "Active",
    requiresReferral: false,
    separateEmDocumented: false,
    status: "Charge review",
    history: created("2026-09-16T06:00:00-04:00"),
  },
  {
    id: "CLM-26-0410",
    patientId: "PT-009",
    dos: "2026-09-10",
    provider: "Dr. Ravi Patel",
    department: "Family Medicine",
    insurerId: "INS-MMC",
    payer: "NY Medicaid Managed Care (teaching plan)",
    memberId: "CHP-48506",
    diagnoses: [
      { code: "Z00.129", display: "Routine child health exam without abnormal findings" },
      { code: "J45.30", display: "Mild persistent asthma, uncomplicated" },
      { code: "Z23", display: "Encounter for immunization" },
    ],
    lines: [
      { line: 1, cpt: "99394", description: "Preventive visit, established patient, age 12–17", modifiers: [], dxPointers: ["Z00.129", "J45.30"], units: 1, charge: 240 },
      { line: 2, cpt: "90686", description: "Influenza vaccine, quadrivalent, preservative-free", modifiers: [], dxPointers: ["Z23"], units: 1, charge: 32 },
      { line: 3, cpt: "90460", description: "Immunization administration with counseling, first component", modifiers: [], dxPointers: ["Z23"], units: 1, charge: 25 },
    ],
    eligibility: "Inactive",
    requiresReferral: false,
    status: "Charge review",
    history: created("2026-09-11T06:00:00-04:00"),
  },
  {
    id: "CLM-26-0418",
    patientId: "PT-010",
    dos: "2026-09-16",
    provider: "Dr. Amara Osei",
    department: "Endocrinology",
    insurerId: "INS-CHMO",
    payer: "Crescent Commercial HMO (fictional)",
    memberId: "CHMO-48543",
    diagnoses: [{ code: "E11.65", display: "Type 2 diabetes mellitus with hyperglycemia" }],
    lines: [
      { line: 1, cpt: "99204", description: "Office visit, new patient, moderate MDM", modifiers: [], dxPointers: ["E11.65"], units: 1, charge: 340 },
    ],
    eligibility: "Active",
    requiresReferral: true,
    status: "Charge review",
    history: created("2026-09-17T06:00:00-04:00"),
  },
  {
    id: "CLM-26-0402",
    patientId: "PT-001",
    dos: "2026-08-10",
    provider: "Dr. Lin Chen",
    department: "Internal Medicine",
    insurerId: "INS-MMC",
    payer: "NY Medicaid Managed Care (teaching plan)",
    memberId: "MCD-48210",
    diagnoses: [{ code: "M75.51", display: "Bursitis of right shoulder" }],
    lines: [
      { line: 1, cpt: "99214", description: "Office visit, established patient, moderate MDM", modifiers: [], dxPointers: ["M75.51"], units: 1, charge: 260 },
    ],
    eligibility: "Active",
    requiresReferral: false,
    status: "Charge review",
    history: created("2026-08-11T06:00:00-04:00"),
  },
  // Denial work queue
  {
    id: "CLM-26-0388",
    patientId: "PT-011",
    dos: "2026-09-10",
    provider: "Dr. Ravi Patel",
    department: "Laboratory",
    insurerId: "INS-CPPO",
    payer: "Crescent Commercial PPO (fictional)",
    memberId: "CPPO-48580",
    diagnoses: [
      { code: "E78.5", display: "Hyperlipidemia, unspecified" },
      { code: "R73.03", display: "Prediabetes" },
    ],
    lines: [
      { line: 1, cpt: "80061", description: "Lipid panel", modifiers: [], dxPointers: [], units: 1, charge: 48, orderingProvider: "Dr. Ravi Patel" },
      { line: 2, cpt: "83036", description: "Hemoglobin A1c", modifiers: [], dxPointers: [], units: 1, charge: 42, orderingProvider: "Dr. Ravi Patel" },
      { line: 3, cpt: "36415", description: "Venipuncture", modifiers: [], dxPointers: [], units: 1, charge: 12 },
    ],
    eligibility: "Active",
    requiresReferral: false,
    status: "Denied",
    denial: { group: "CO", carc: "16", plain: "Claim lacks information needed for adjudication. RARC M76: missing or incomplete diagnosis for the lab services.", rarc: "M76", deniedAt: "2026-09-15", amount: 102 },
    history: [{ at: "2026-09-11T06:00:00-04:00", change: "Submitted before the scrubber pointer rule was enabled" }, { at: "2026-09-15T10:00:00-04:00", change: "835 remittance: denied CO-16 / M76" }],
  },
  {
    id: "CLM-26-0391",
    patientId: "PT-004",
    dos: "2026-09-11",
    provider: "Dr. Ravi Patel",
    department: "Family Medicine",
    insurerId: "INS-MMC",
    payer: "NY Medicaid Managed Care (teaching plan)",
    memberId: "MCD-48321",
    diagnoses: [{ code: "D50.9", display: "Iron deficiency anemia, unspecified" }],
    lines: [
      { line: 1, cpt: "99213", description: "Office visit, established patient, low MDM", modifiers: [], dxPointers: ["D50.9"], units: 1, charge: 185 },
      { line: 2, cpt: "85025", description: "Complete blood count with differential", modifiers: [], dxPointers: [], units: 1, charge: 22, orderingProvider: "Dr. Ravi Patel" },
      { line: 3, cpt: "82728", description: "Ferritin", modifiers: [], dxPointers: [], units: 1, charge: 30, orderingProvider: "Dr. Ravi Patel" },
    ],
    eligibility: "Active",
    requiresReferral: false,
    status: "Denied",
    denial: { group: "CO", carc: "16", plain: "Claim lacks information needed for adjudication. RARC M76 on lines 2–3: missing diagnosis for the lab services. Line 1 paid.", rarc: "M76", deniedAt: "2026-09-17", amount: 52 },
    history: [{ at: "2026-09-12T06:00:00-04:00", change: "Submitted" }, { at: "2026-09-17T10:00:00-04:00", change: "835 remittance: lines 2–3 denied CO-16 / M76" }],
  },
  {
    id: "CLM-26-0379",
    patientId: "PT-006",
    dos: "2026-08-03",
    provider: "Dr. Ravi Patel",
    department: "Family Medicine",
    insurerId: "INS-CPPO",
    payer: "Crescent Commercial PPO (fictional)",
    memberId: "CPPO-48395",
    diagnoses: [{ code: "E03.9", display: "Hypothyroidism, unspecified" }],
    lines: [
      { line: 1, cpt: "99214", description: "Office visit, established patient, moderate MDM", modifiers: [], dxPointers: ["E03.9"], units: 1, charge: 260 },
      { line: 2, cpt: "84443", description: "Thyroid-stimulating hormone (TSH)", modifiers: [], dxPointers: [], units: 1, charge: 35, orderingProvider: "Dr. Ravi Patel" },
    ],
    eligibility: "Active",
    requiresReferral: false,
    status: "Denied",
    denial: { group: "CO", carc: "16", plain: "Claim lacks information needed for adjudication. RARC M76 on line 2: missing diagnosis for the TSH.", rarc: "M76", deniedAt: "2026-09-16", amount: 35 },
    history: [{ at: "2026-08-04T06:00:00-04:00", change: "Submitted" }, { at: "2026-09-16T10:00:00-04:00", change: "835 remittance: line 2 denied CO-16 / M76" }],
  },
  {
    id: "CLM-26-0366",
    patientId: "PT-005",
    dos: "2026-08-28",
    provider: "Dr. Lin Chen",
    department: "Cardiology testing",
    insurerId: "INS-MA",
    payer: "Medicare Advantage HMO (teaching plan)",
    memberId: "MCR-48358",
    diagnoses: [{ code: "I50.22", display: "Chronic systolic (congestive) heart failure" }],
    lines: [
      { line: 1, cpt: "93306", description: "Transthoracic echocardiogram, complete, with Doppler", modifiers: [], dxPointers: ["I50.22"], units: 1, charge: 1150 },
    ],
    eligibility: "Active",
    requiresReferral: false,
    requiresPriorAuth: true,
    status: "Denied",
    denial: { group: "CO", carc: "197", plain: "Precertification/authorization absent. The Medicare Advantage plan requires prior authorization for outpatient echocardiography.", deniedAt: "2026-09-14", amount: 1150 },
    history: [{ at: "2026-08-29T06:00:00-04:00", change: "Submitted" }, { at: "2026-09-14T10:00:00-04:00", change: "835 remittance: denied CO-197" }],
  },
];

/** Values the learner can apply when correcting scrubber edits. */
export const claimFixes: Record<string, { eligibility?: { memberId: string; note: string }; referralNumber?: string; documentation?: string }> = {
  "CLM-26-0410": { eligibility: { memberId: "CHP-77120", note: "Child Health Plus recertified 9/1 with a new member ID (271 response, simulated)." } },
  "CLM-26-0418": { referralNumber: "REF-2026-0908-KIM" },
  "CLM-26-0415": { documentation: "Note NOTE-SEED-011A documents a separate problem: elevated BP evaluation with a home-monitoring plan." },
};
