/**
 * In Basket seed: results, patient advice requests, refills, co-sign requests,
 * and AI-drafted replies. Pools: the physician/APP team inbox and the nurse triage pool.
 */
import type { InBasketItem, PortalMessage } from "../types";

/** Portal messages added in v4 (appended to the v3 messages MSG-001…MSG-003). */
export const v4Messages: PortalMessage[] = [
  { id: "MSG-004", patientId: "PT-003", from: "Elena Garcia", subject: "Pregunta sobre mi medicina", body: "Hola, mis lecturas de presión en casa siguen altas (150/92 esta mañana). ¿Debo tomar más amlodipina? Gracias.", date: "2026-09-16", status: "New" },
  { id: "MSG-005", patientId: "PT-009", from: "Carmen Rivera (proxy)", subject: "Inhalador para la escuela", body: "Buenas tardes. Mateo necesita un inhalador extra para la escuela y el formulario firmado. ¿Pueden enviarlo a la farmacia?", date: "2026-09-17", status: "New", proxy: true },
  { id: "MSG-006", patientId: "PT-002", from: "Marcus Reed", subject: "Is my potassium dangerous?", body: "I saw my potassium was flagged high in the portal on Saturday. Is that dangerous? Should I keep taking the lisinopril you increased?", date: "2026-09-20", status: "New" },
  { id: "MSG-007", patientId: "PT-010", from: "Grace Kim", subject: "Metformin refill to my new pharmacy", body: "I moved my prescriptions to Walgreens on Northern Blvd. Can you send my metformin there? I have 3 days left.", date: "2026-09-20", status: "New" },
  { id: "MSG-008", patientId: "PT-007", from: "Devon Brooks", subject: "Flu shot at the pharmacy?", body: "Can I get my flu shot at my pharmacy instead of coming in? I'm free this week.", date: "2026-09-20", status: "New" },
];

export const inBasketItems: InBasketItem[] = [
  {
    id: "IB-001",
    kind: "Result",
    pool: "Physician/APP",
    patientId: "PT-002",
    subject: "CRITICAL: Potassium 6.1 mmol/L",
    body: "Basic metabolic panel collected Saturday 9/19 at 07:42 (Saturday lab hours). Lab comment: critical value; phone notification attempted to the ordering clinic at 08:10, reached the after-hours voicemail.",
    from: "Fordham Health Laboratory",
    receivedAt: "2026-09-19T08:05:00-04:00",
    recipient: "Sam Brooks, NP (out of office 9/18–9/21 · no delegate set)",
    priority: "Critical",
    status: "Open",
    result: { name: "Potassium", value: "6.1", unit: "mmol/L", range: "3.5–5.1 (critical ≥ 6.0)", flag: "Critical high", collectedAt: "2026-09-19T07:42:00-04:00", orderedBy: "Sam Brooks, NP" },
    routingNote: "Routed to the ordering provider's personal In Basket. The critical-result escalation rule applies to inpatient locations only.",
  },
  {
    id: "IB-002",
    kind: "Result",
    pool: "Physician/APP",
    patientId: "PT-005",
    subject: "BNP 1,480 pg/mL (ED 9/20)",
    body: "Resulted during the ED visit before admission. Patient is now inpatient on 4 West under Dr. Morales; PCP copy for awareness.",
    from: "Fordham Health Laboratory",
    receivedAt: "2026-09-20T17:30:00-04:00",
    recipient: "Dr. Lin Chen (PCP copy)",
    priority: "High",
    status: "Open",
    result: { name: "BNP", value: "1480", unit: "pg/mL", range: "< 100", flag: "High", collectedAt: "2026-09-20T16:55:00-04:00", orderedBy: "ED physician" },
  },
  {
    id: "IB-003",
    kind: "Result",
    pool: "Physician/APP",
    patientId: "PT-010",
    subject: "Hemoglobin A1c 9.1%",
    body: "Up from 8.6% in March. Endocrinology consult completed 9/16.",
    from: "Fordham Health Laboratory",
    receivedAt: "2026-09-08T14:12:00-04:00",
    recipient: "Dr. Lin Chen",
    priority: "Routine",
    status: "Open",
    result: { name: "Hemoglobin A1c", value: "9.1", unit: "%", range: "4.0–5.6", flag: "High", collectedAt: "2026-09-08T09:30:00-04:00", orderedBy: "Dr. Lin Chen" },
  },
  {
    id: "IB-004",
    kind: "Advice request",
    pool: "Nurse",
    patientId: "PT-003",
    subject: "Home blood pressure readings",
    body: "My readings this week were 148/90, 145/88, and 150/92. Should I change my medicine?",
    from: "Elena Garcia (portal)",
    receivedAt: "2026-09-20T07:40:00-04:00",
    recipient: "Clinic nurse triage pool",
    priority: "Routine",
    status: "Open",
    messageId: "MSG-001",
  },
  {
    id: "IB-005",
    kind: "Refill request",
    pool: "Physician/APP",
    patientId: "PT-010",
    subject: "Refill: metformin 1,000 mg",
    body: "Patient requests transfer to a new pharmacy; 3 days of tablets left.",
    from: "Grace Kim (portal)",
    receivedAt: "2026-09-20T19:05:00-04:00",
    recipient: "Dr. Lin Chen",
    priority: "Routine",
    status: "Open",
    refill: { medication: "Metformin 1,000 mg tablet, 1 tablet twice daily, #60", pharmacy: "Walgreens #10421, 150-40 Northern Blvd, Flushing (new)", lastFilled: "2026-08-22", note: "Previous pharmacy: CVS #2214, Broadway" },
  },
  {
    id: "IB-006",
    kind: "Refill request",
    pool: "Nurse",
    patientId: "PT-011",
    subject: "Refill: atorvastatin 10 mg (protocol)",
    body: "Pharmacy-initiated renewal. Lipid panel 9/10: LDL 142 mg/dL. Nurse refill protocol allows one 90-day renewal if seen within 12 months.",
    from: "Pharmacy e-prescribing (NCPDP)",
    receivedAt: "2026-09-19T11:22:00-04:00",
    recipient: "Clinic nurse triage pool",
    priority: "Routine",
    status: "Open",
    refill: { medication: "Atorvastatin 10 mg tablet, 1 tablet nightly, #90", pharmacy: "Duane Reade #14022, 3rd Ave", lastFilled: "2026-06-18" },
  },
  {
    id: "IB-007",
    kind: "Co-sign",
    pool: "Physician/APP",
    patientId: "PT-011",
    subject: "Co-sign: office note by Sam Brooks, NP (9/15)",
    body: "Cerumen removal and elevated BP reading. Supervising physician co-signature requested.",
    from: "Sam Brooks, NP",
    receivedAt: "2026-09-15T11:00:00-04:00",
    recipient: "Dr. Lin Chen",
    priority: "Routine",
    status: "Open",
    noteId: "NOTE-SEED-011A",
  },
  {
    id: "IB-008",
    kind: "AI draft reply",
    pool: "Physician/APP",
    patientId: "PT-002",
    subject: "Is my potassium dangerous?",
    body: "I saw my potassium was flagged high in the portal on Saturday. Is that dangerous? Should I keep taking the lisinopril you increased?",
    from: "Marcus Reed (portal)",
    receivedAt: "2026-09-20T09:14:00-04:00",
    recipient: "Dr. Lin Chen",
    priority: "High",
    status: "Open",
    messageId: "MSG-006",
    aiDraft: {
      model: "Reply drafting assistant (simulated)",
      generatedAt: "2026-09-20T09:14:30-04:00",
      text: "Hi Marcus, thanks for reaching out. Your potassium is a little high, which is common and usually nothing to worry about. You can stop taking your lisinopril until your next appointment. Try to eat more bananas and oranges to keep your energy up. See you at your visit!",
    },
  },
  {
    id: "IB-009",
    kind: "AI draft reply",
    pool: "Physician/APP",
    patientId: "PT-010",
    subject: "Metformin refill to my new pharmacy",
    body: "I moved my prescriptions to Walgreens on Northern Blvd. Can you send my metformin there? I have 3 days left.",
    from: "Grace Kim (portal)",
    receivedAt: "2026-09-20T19:02:00-04:00",
    recipient: "Dr. Lin Chen",
    priority: "Routine",
    status: "Open",
    messageId: "MSG-007",
    aiDraft: {
      model: "Reply drafting assistant (simulated)",
      generatedAt: "2026-09-20T19:02:40-04:00",
      text: "Hello Grace, your metformin refill has been sent to CVS Pharmacy on Broadway. It should be ready tomorrow. Happy early birthday!",
    },
  },
  {
    id: "IB-010",
    kind: "AI draft reply",
    pool: "Nurse",
    patientId: "PT-003",
    subject: "Pregunta sobre mi medicina",
    body: "Hola, mis lecturas de presión en casa siguen altas (150/92 esta mañana). ¿Debo tomar más amlodipina? Gracias.",
    from: "Elena Garcia (portal)",
    receivedAt: "2026-09-16T08:03:00-04:00",
    recipient: "General message pool (no routing rule matched)",
    priority: "Routine",
    status: "Open",
    messageId: "MSG-004",
    routingNote: "No routing rule matched this message, so it fell to the unowned general pool (72-hour aging).",
    aiDraft: {
      model: "Reply drafting assistant (simulated)",
      generatedAt: "2026-09-16T08:04:10-04:00",
      text: "Thank you for your message. Please increase your amlodipine to 10 mg daily and keep checking your blood pressure twice a day. Let us know if you have questions.",
    },
  },
  {
    id: "IB-011",
    kind: "AI draft reply",
    pool: "Nurse",
    patientId: "PT-007",
    subject: "Flu shot at the pharmacy?",
    body: "Can I get my flu shot at my pharmacy instead of coming in? I'm free this week.",
    from: "Devon Brooks (portal)",
    receivedAt: "2026-09-20T12:40:00-04:00",
    recipient: "Clinic nurse triage pool",
    priority: "Routine",
    status: "Open",
    messageId: "MSG-008",
    aiDraft: {
      model: "Reply drafting assistant (simulated)",
      generatedAt: "2026-09-20T12:40:20-04:00",
      text: "Hi Devon, yes, you can get your flu vaccine at a pharmacy this week. Please tell us the date and pharmacy afterward, or ask the pharmacy to report it to the state immunization registry, so we can update your record.",
    },
  },
  {
    id: "IB-012",
    kind: "Advice request",
    pool: "Nurse",
    patientId: "PT-009",
    subject: "Can I see Mateo's visit note?",
    body: "I can see the vaccine record but not the notes from Mateo's visit last week. Can you release the full note to me? — Carmen Rivera (proxy)",
    from: "Carmen Rivera (proxy, portal)",
    receivedAt: "2026-09-18T20:15:00-04:00",
    recipient: "Clinic nurse triage pool",
    priority: "Routine",
    status: "Open",
  },
];

export const INBASKET_OUTCOMES: Record<InBasketItem["kind"], string[]> = {
  Result: ["Acknowledge and create follow-up task", "Acknowledge only (no action needed)"],
  "Advice request": ["Reply to patient", "Route to clinician", "Route to front desk"],
  "Refill request": ["Approve refill", "Approve per nurse protocol", "Deny and message patient", "Route to prescriber"],
  "Co-sign": ["Co-sign note"],
  "AI draft reply": ["Send as drafted", "Edit and send", "Discard and write own reply", "Discard and route to clinician"],
};

export const AI_REPLY_ISSUES = [
  "Unsafe or incorrect clinical advice",
  "Wrong patient or wrong detail",
  "Language or reading-level mismatch",
  "Makes a decision no clinician has made",
  "Missing escalation or safety-net advice",
] as const;
