/**
 * Hand-authored synthetic charts for the twelve FordMS patients.
 * Identity fields (id, MRN, name, DOB) and the PT-001 / PT-012 duplicate signals
 * (address, phone) are fixed: FORDMS-A1 and existing workspaces depend on them.
 * Every person, result, and encounter here is fictional.
 */
import type { NoteVersion, Patient } from "../types";

const LOINC = {
  potassium: "2823-3",
  sodium: "2951-2",
  creatinine: "2160-0",
  egfr: "98979-8",
  glucose: "2345-7",
  a1c: "4548-4",
  ldl: "13457-7",
  hgb: "718-7",
  wbc: "6690-2",
  ferritin: "2276-4",
  bnp: "30934-4",
  lactate: "2524-7",
  procalcitonin: "33959-8",
  tsh: "3016-3",
  uacr: "9318-7",
  vitd: "1989-3",
};

function note(partial: Omit<NoteVersion, "kind"> & { kind?: NoteVersion["kind"] }): NoteVersion {
  return { kind: "Signed", ...partial };
}

export const seedPatients: Patient[] = [
  {
    id: "PT-001",
    mrn: "6105100",
    name: "Liu Huang",
    dob: "1984-03-19",
    sex: "Female",
    pronouns: "she/her",
    language: "Mandarin",
    interpreterNeeded: true,
    address: "120 Example Avenue, New York, NY 10000",
    phone: "(212) 555-1100",
    insurance: "NY Medicaid Managed Care (teaching plan)",
    insurerId: "INS-MMC",
    memberId: "MCD-48210",
    pcp: "Dr. Lin Chen",
    careTeam: [
      { name: "Dr. Lin Chen", role: "PCP · Internal medicine" },
      { name: "Maria Diaz", role: "Front desk lead" },
    ],
    flags: ["Interpreter: Mandarin"],
    problems: [
      { code: "M75.51", display: "Bursitis of right shoulder", onset: "2026-08-10", status: "Active" },
      { code: "J45.20", display: "Mild intermittent asthma, uncomplicated", onset: "2015-05-12", status: "Active" },
    ],
    medications: [
      { name: "Albuterol HFA 90 mcg/actuation inhaler", sig: "2 puffs by mouth every 4–6 hours as needed for wheeze", status: "Active", dose: "180 mcg", route: "Inhaled", frequency: "Every 4–6 h PRN", prescriber: "Dr. Lin Chen", indication: "Asthma" },
      { name: "Acetaminophen 500 mg tablet", sig: "2 tablets by mouth every 8 hours as needed for shoulder pain (max 3 g/day)", status: "Active", dose: "1,000 mg", route: "PO", frequency: "Every 8 h PRN", prescriber: "Dr. Lin Chen", indication: "Shoulder pain" },
    ],
    allergies: [{ allergen: "Penicillin", reaction: "Hives", severity: "Severe", type: "Allergy", verified: "2019-04-02" }],
    vitals: [
      { date: "2026-09-21", bp: "124/78", hr: 72, weight: "132 lb", temp: "36.8 °C", rr: 16, spo2: 99, bmi: "23.4" },
      { date: "2026-08-10", bp: "126/80", hr: 76, weight: "133 lb", temp: "36.7 °C", rr: 16, spo2: 99, bmi: "23.6" },
      { date: "2026-03-02", bp: "120/74", hr: 70, weight: "131 lb", temp: "36.6 °C", rr: 14, spo2: 98, bmi: "23.2" },
      { date: "2025-11-03", bp: "118/76", hr: 68, weight: "130 lb", temp: "36.8 °C", rr: 14, spo2: 99, bmi: "23.0" },
    ],
    results: [
      { date: "2026-03-02", name: "Hemoglobin A1c", value: "5.4", unit: "%", range: "4.0–5.6", flag: "", status: "Final", loinc: LOINC.a1c, orderedBy: "Dr. Lin Chen" },
      { date: "2026-03-02", name: "Hemoglobin", value: "13.1", unit: "g/dL", range: "12.0–15.5", flag: "", status: "Final", loinc: LOINC.hgb, orderedBy: "Dr. Lin Chen" },
      { date: "2026-03-02", name: "TSH", value: "1.8", unit: "mIU/L", range: "0.4–4.0", flag: "", status: "Final", loinc: LOINC.tsh, orderedBy: "Dr. Lin Chen" },
    ],
    encounters: [
      { id: "ENC-001-1", date: "2026-08-10", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Right shoulder pain, 3 weeks", status: "Completed" },
      { id: "ENC-001-2", date: "2026-09-14", type: "Telehealth", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Shoulder follow-up (ambient AI scribe used)", status: "Completed" },
      { id: "ENC-001-3", date: "2026-09-18", type: "Urgent care (external)", provider: "Hudson Urgent Care", department: "External", reason: "Shoulder pain flare; naproxen started", status: "Completed" },
      { id: "ENC-001-4", date: "2026-09-21", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Shoulder follow-up, in person", status: "Scheduled" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-001A",
        author: "Dr. Lin Chen",
        recordedAt: "2026-08-10T10:42:00-04:00",
        encounterId: "ENC-001-1",
        source: "Typed",
        subjective: "Three weeks of right shoulder pain after lifting boxes while restocking shelves at work. Worse reaching overhead. No fall, no numbness or weakness. Visit conducted with a Mandarin video interpreter.",
        objective: "BP 126/80, HR 76. Tenderness over the right lateral shoulder; painful arc 70–120 degrees; strength 5/5. Neurologic examination not performed.",
        assessment: "Right subacromial bursitis (M75.51).",
        plan: "Ice, activity modification, acetaminophen as needed. Physical therapy if not improved in 4 weeks. Return in 4–6 weeks.",
      }),
      note({
        id: "NOTE-SEED-001B",
        author: "Dr. Lin Chen",
        recordedAt: "2026-09-14T16:05:00-04:00",
        encounterId: "ENC-001-2",
        source: "AI scribe draft accepted",
        subjective: "Patient reports persistent left shoulder pain despite rest. Interpreter used.",
        objective: "Telehealth visit; no in-person examination.",
        assessment: "Bursitis of left shoulder, not improving.",
        plan: "Physical therapy referral placed. In-person follow-up 9/21.",
      }),
    ],
    duplicateCandidate: "PT-012",
  },
  {
    id: "PT-002",
    mrn: "6105101",
    name: "Marcus Reed",
    dob: "1968-11-02",
    sex: "Male",
    pronouns: "he/him",
    language: "English",
    address: "2150 Adam Clayton Powell Jr Blvd, Apt 6C, New York, NY 10027",
    phone: "(212) 555-1101",
    insurance: "Crescent Commercial HMO (fictional)",
    insurerId: "INS-CHMO",
    memberId: "CHMO-48247",
    pcp: "Dr. Lin Chen",
    careTeam: [
      { name: "Dr. Lin Chen", role: "PCP · Internal medicine" },
      { name: "Sam Brooks, NP", role: "Hypertension follow-up" },
    ],
    flags: ["Critical result unacknowledged"],
    problems: [
      { code: "I10", display: "Essential (primary) hypertension", onset: "2014-06-02", status: "Active" },
      { code: "E78.5", display: "Hyperlipidemia, unspecified", onset: "2016-01-19", status: "Active" },
    ],
    medications: [
      { name: "Lisinopril 20 mg tablet", sig: "1 tablet by mouth once daily (increased from 10 mg on 9/14)", status: "Active", dose: "20 mg", route: "PO", frequency: "Daily", prescriber: "Sam Brooks, NP", indication: "Hypertension" },
      { name: "Atorvastatin 20 mg tablet", sig: "1 tablet by mouth at bedtime", status: "Active", dose: "20 mg", route: "PO", frequency: "Nightly", prescriber: "Dr. Lin Chen", indication: "Hyperlipidemia" },
    ],
    allergies: [{ allergen: "No known drug allergies", reaction: "", severity: "None", type: "Allergy", verified: "2026-09-14" }],
    vitals: [
      { date: "2026-09-14", bp: "148/92", hr: 76, weight: "214 lb", temp: "36.7 °C", rr: 16, spo2: 98, bmi: "31.6" },
      { date: "2026-06-02", bp: "142/88", hr: 74, weight: "212 lb", temp: "36.6 °C", rr: 16, spo2: 98, bmi: "31.3" },
      { date: "2026-03-09", bp: "150/94", hr: 80, weight: "216 lb", temp: "36.8 °C", rr: 16, spo2: 97, bmi: "31.9" },
      { date: "2025-12-01", bp: "146/90", hr: 78, weight: "215 lb", temp: "36.7 °C", rr: 14, spo2: 98, bmi: "31.7" },
    ],
    results: [
      { date: "2026-09-19", name: "Potassium", value: "6.1", unit: "mmol/L", range: "3.5–5.1 (critical ≥ 6.0)", flag: "High", status: "Final", loinc: LOINC.potassium, orderedBy: "Sam Brooks, NP" },
      { date: "2026-09-19", name: "Creatinine", value: "1.3", unit: "mg/dL", range: "0.74–1.35", flag: "", status: "Final", loinc: LOINC.creatinine, orderedBy: "Sam Brooks, NP" },
      { date: "2026-09-19", name: "eGFR", value: "64", unit: "mL/min/1.73m²", range: "> 60", flag: "", status: "Final", loinc: LOINC.egfr, orderedBy: "Sam Brooks, NP" },
      { date: "2026-09-19", name: "Sodium", value: "138", unit: "mmol/L", range: "135–145", flag: "", status: "Final", loinc: LOINC.sodium, orderedBy: "Sam Brooks, NP" },
      { date: "2026-06-02", name: "Potassium", value: "5.3", unit: "mmol/L", range: "3.5–5.1", flag: "High", status: "Final", loinc: LOINC.potassium, orderedBy: "Dr. Lin Chen" },
      { date: "2026-06-02", name: "LDL cholesterol", value: "96", unit: "mg/dL", range: "< 100", flag: "", status: "Final", loinc: LOINC.ldl, orderedBy: "Dr. Lin Chen" },
    ],
    encounters: [
      { id: "ENC-002-1", date: "2026-06-02", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Annual visit", status: "Completed" },
      { id: "ENC-002-2", date: "2026-09-14", type: "Office visit", provider: "Sam Brooks, NP", department: "Internal Medicine", reason: "Blood pressure follow-up", status: "Completed" },
      { id: "ENC-002-3", date: "2026-09-19", type: "Nurse visit", provider: "Fordham Health Lab", department: "Laboratory", reason: "BMP draw (Saturday lab hours)", status: "Completed" },
      { id: "ENC-002-4", date: "2026-09-21", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Follow-up", status: "Scheduled" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-002A",
        author: "Sam Brooks, NP",
        recordedAt: "2026-09-14T11:20:00-04:00",
        encounterId: "ENC-002-2",
        source: "Typed",
        subjective: "Home BP 140s–150s/90s. Adherent to lisinopril 10 mg. Uses a salt substitute (potassium chloride) since June.",
        objective: "BP 148/92, repeat 146/90. HR 76. BMI 31.6.",
        assessment: "Essential hypertension, above goal. Prior potassium 5.3 in June.",
        plan: "Increase lisinopril to 20 mg daily. Stop the salt substitute. BMP in 5 days (Saturday lab hours). Follow-up with Dr. Chen 9/21.",
      }),
    ],
  },
  {
    id: "PT-003",
    mrn: "6105102",
    name: "Elena Garcia",
    dob: "1976-07-14",
    sex: "Female",
    pronouns: "she/her",
    language: "Spanish",
    interpreterNeeded: true,
    address: "561 West 180th Street, Apt 3B, New York, NY 10033",
    phone: "(212) 555-1102",
    insurance: "NY Medicaid Managed Care (teaching plan)",
    insurerId: "INS-MMC",
    memberId: "MMC-48284",
    pcp: "Dr. Ravi Patel",
    careTeam: [
      { name: "Dr. Ravi Patel", role: "PCP · Family medicine" },
      { name: "Ana Torres, RN", role: "Clinic nurse (Spanish-speaking)" },
    ],
    flags: ["Interpreter: Spanish"],
    problems: [
      { code: "I10", display: "Essential (primary) hypertension", onset: "2021-04-08", status: "Active" },
      { code: "E11.9", display: "Type 2 diabetes mellitus without complications", onset: "2023-02-15", status: "Active" },
    ],
    medications: [
      { name: "Amlodipine 5 mg tablet", sig: "1 tablet by mouth once daily", status: "Active", dose: "5 mg", route: "PO", frequency: "Daily", prescriber: "Dr. Lin Chen", indication: "Hypertension" },
      { name: "Metformin 500 mg tablet", sig: "1 tablet by mouth twice daily with meals", status: "Active", dose: "500 mg", route: "PO", frequency: "BID", prescriber: "Dr. Lin Chen", indication: "Type 2 diabetes" },
    ],
    allergies: [{ allergen: "Lisinopril (ACE inhibitor)", reaction: "Dry cough", severity: "Mild", type: "Intolerance", verified: "2022-01-11" }],
    vitals: [
      { date: "2026-09-14", bp: "132/78", hr: 78, weight: "168 lb", temp: "36.6 °C", rr: 16, spo2: 98, bmi: "29.8" },
      { date: "2026-06-15", bp: "138/84", hr: 80, weight: "170 lb", temp: "36.7 °C", rr: 16, spo2: 98, bmi: "30.1" },
      { date: "2026-03-10", bp: "136/82", hr: 76, weight: "171 lb", temp: "36.8 °C", rr: 14, spo2: 99, bmi: "30.3" },
    ],
    results: [
      { date: "2026-09-14", name: "Hemoglobin A1c", value: "8.2", unit: "%", range: "4.0–5.6", flag: "High", status: "Final", loinc: LOINC.a1c, orderedBy: "Dr. Ravi Patel" },
      { date: "2026-09-14", name: "Creatinine", value: "0.8", unit: "mg/dL", range: "0.59–1.04", flag: "", status: "Final", loinc: LOINC.creatinine, orderedBy: "Dr. Ravi Patel" },
      { date: "2026-09-14", name: "Urine albumin/creatinine ratio", value: "18", unit: "mg/g", range: "< 30", flag: "", status: "Final", loinc: LOINC.uacr, orderedBy: "Dr. Ravi Patel" },
      { date: "2026-03-10", name: "Hemoglobin A1c", value: "7.6", unit: "%", range: "4.0–5.6", flag: "High", status: "Final", loinc: LOINC.a1c, orderedBy: "Dr. Lin Chen" },
    ],
    encounters: [
      { id: "ENC-003-1", date: "2026-03-10", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Diabetes follow-up", status: "Completed" },
      { id: "ENC-003-2", date: "2026-09-14", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "Transfer of care; labs", status: "Completed" },
      { id: "ENC-003-3", date: "2026-09-21", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "New to provider: hypertension and diabetes", status: "Scheduled" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-003A",
        author: "Dr. Ravi Patel",
        recordedAt: "2026-09-14T15:10:00-04:00",
        encounterId: "ENC-003-2",
        source: "Typed",
        subjective: "Transferring care to family medicine. Checks BP at home most mornings. Spanish interpreter (in person) used.",
        objective: "BP 132/78, HR 78. Foot exam normal monofilament.",
        assessment: "Hypertension, controlled in office; home readings to be reviewed. Type 2 diabetes, A1c 8.2%.",
        plan: "Send home BP log through the portal. Diabetes education referral. Full visit 9/21.",
      }),
    ],
  },
  {
    id: "PT-004",
    mrn: "6105103",
    name: "Amina Yusuf",
    dob: "1992-01-25",
    sex: "Female",
    pronouns: "she/her",
    language: "Somali",
    interpreterNeeded: true,
    address: "1780 Walton Avenue, Apt 5F, Bronx, NY 10453",
    phone: "(212) 555-1103",
    insurance: "NY Medicaid Managed Care (teaching plan)",
    insurerId: "INS-MMC",
    memberId: "MCD-48321",
    pcp: "Dr. Ravi Patel",
    careTeam: [{ name: "Dr. Ravi Patel", role: "PCP · Family medicine" }],
    flags: ["Interpreter: Somali", "Coverage recertification"],
    problems: [
      { code: "D50.9", display: "Iron deficiency anemia, unspecified", onset: "2025-07-22", status: "Active" },
      { code: "E55.9", display: "Vitamin D deficiency, unspecified", onset: "2025-07-22", status: "Active" },
    ],
    medications: [
      { name: "Ferrous sulfate 325 mg tablet", sig: "1 tablet by mouth once daily with orange juice", status: "Active", dose: "325 mg", route: "PO", frequency: "Daily", prescriber: "Dr. Ravi Patel", indication: "Iron deficiency" },
      { name: "Cholecalciferol 2,000 unit capsule", sig: "1 capsule by mouth once daily", status: "Active", dose: "2,000 units", route: "PO", frequency: "Daily", prescriber: "Dr. Ravi Patel", indication: "Vitamin D deficiency" },
    ],
    allergies: [{ allergen: "No known drug allergies", reaction: "", severity: "None", type: "Allergy", verified: "2026-09-11" }],
    vitals: [
      { date: "2026-09-11", bp: "112/70", hr: 84, weight: "141 lb", temp: "36.9 °C", rr: 16, spo2: 99, bmi: "24.2" },
      { date: "2026-02-18", bp: "108/68", hr: 88, weight: "139 lb", temp: "36.7 °C", rr: 16, spo2: 99, bmi: "23.9" },
      { date: "2025-07-22", bp: "110/66", hr: 92, weight: "136 lb", temp: "36.8 °C", rr: 16, spo2: 99, bmi: "23.4" },
    ],
    results: [
      { date: "2026-09-11", name: "Hemoglobin", value: "10.9", unit: "g/dL", range: "12.0–15.5", flag: "Low", status: "Final", loinc: LOINC.hgb, orderedBy: "Dr. Ravi Patel" },
      { date: "2026-09-11", name: "Ferritin", value: "9", unit: "ng/mL", range: "15–150", flag: "Low", status: "Final", loinc: LOINC.ferritin, orderedBy: "Dr. Ravi Patel" },
      { date: "2026-02-18", name: "25-hydroxy vitamin D", value: "24", unit: "ng/mL", range: "30–100", flag: "Low", status: "Final", loinc: LOINC.vitd, orderedBy: "Dr. Ravi Patel" },
    ],
    encounters: [
      { id: "ENC-004-1", date: "2026-09-11", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "Fatigue; anemia follow-up", status: "Completed" },
      { id: "ENC-004-2", date: "2026-09-21", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "Urgent: dysuria for 2 days", status: "Scheduled" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-004A",
        author: "Dr. Ravi Patel",
        recordedAt: "2026-09-11T12:30:00-04:00",
        encounterId: "ENC-004-1",
        source: "Typed",
        subjective: "Fatigue for two months. Taking iron most days; stomach upset when taken without food. Somali phone interpreter used.",
        objective: "BP 112/70, HR 84. Conjunctival pallor. Hemoglobin 10.9, ferritin 9.",
        assessment: "Iron deficiency anemia, incompletely treated.",
        plan: "Take iron every other day with food and vitamin C. Recheck CBC and ferritin in 8 weeks. Note: Medicaid plan shows recertification due; front desk to verify coverage.",
      }),
    ],
  },
  {
    id: "PT-005",
    mrn: "6105104",
    name: "James O'Brien",
    dob: "1959-05-08",
    sex: "Male",
    pronouns: "he/him",
    language: "English",
    address: "88 Morton Street, Apt 2R, New York, NY 10014",
    phone: "(212) 555-1104",
    insurance: "Medicare Advantage HMO (teaching plan)",
    insurerId: "INS-MA",
    memberId: "MCR-48358",
    pcp: "Dr. Lin Chen",
    careTeam: [
      { name: "Dr. Ana Morales", role: "Attending hospitalist" },
      { name: "Dr. Lin Chen", role: "PCP · Internal medicine" },
      { name: "Kevin Osei, RN", role: "Primary nurse, 4 West" },
      { name: "Jordan Park, RN", role: "Charge nurse, 4 West" },
    ],
    codeStatus: "Full code",
    location: "4 West · Rm 412-B",
    admittedAt: "2026-09-20T18:40:00-04:00",
    weightKg: 71.2,
    flags: ["Fall risk", "Insulin", "Heart failure"],
    problems: [
      { code: "I50.23", display: "Acute on chronic systolic (congestive) heart failure", onset: "2026-09-20", status: "Active" },
      { code: "E11.22", display: "Type 2 diabetes mellitus with diabetic chronic kidney disease", onset: "2012-03-01", status: "Active" },
      { code: "I12.9", display: "Hypertensive chronic kidney disease with stage 1–4 CKD", onset: "2019-10-14", status: "Active" },
      { code: "N18.31", display: "Chronic kidney disease, stage 3a", onset: "2021-05-20", status: "Active" },
      { code: "E78.5", display: "Hyperlipidemia, unspecified", onset: "2010-08-09", status: "Active" },
    ],
    medications: [
      { name: "Furosemide 40 mg tablet", sig: "1 tablet by mouth once daily (inpatient: IV)", status: "Active", dose: "40 mg", route: "PO", frequency: "Daily", prescriber: "Dr. Lin Chen", indication: "Heart failure" },
      { name: "Carvedilol 12.5 mg tablet", sig: "1 tablet by mouth twice daily with food", status: "Active", dose: "12.5 mg", route: "PO", frequency: "BID", prescriber: "Dr. Lin Chen", indication: "Heart failure" },
      { name: "Lisinopril 20 mg tablet", sig: "1 tablet by mouth once daily (held on admission for potassium 5.4)", status: "On hold", dose: "20 mg", route: "PO", frequency: "Daily", prescriber: "Dr. Lin Chen", indication: "Hypertension / HF" },
      { name: "Empagliflozin 10 mg tablet", sig: "1 tablet by mouth once daily", status: "Active", dose: "10 mg", route: "PO", frequency: "Daily", prescriber: "Dr. Lin Chen", indication: "Diabetes / HF / CKD" },
      { name: "Insulin glargine 100 units/mL pen", sig: "18 units subcutaneously at bedtime", status: "Active", dose: "18 units", route: "SC", frequency: "Nightly", prescriber: "Dr. Lin Chen", indication: "Type 2 diabetes" },
      { name: "Metformin 500 mg tablet", sig: "1 tablet by mouth twice daily (held inpatient; eGFR 50)", status: "On hold", dose: "500 mg", route: "PO", frequency: "BID", prescriber: "Dr. Lin Chen", indication: "Type 2 diabetes" },
      { name: "Hydralazine 25 mg tablet", sig: "1 tablet by mouth three times daily", status: "Active", dose: "25 mg", route: "PO", frequency: "TID", prescriber: "Dr. Ana Morales", indication: "Afterload reduction" },
      { name: "Atorvastatin 40 mg tablet", sig: "1 tablet by mouth at bedtime", status: "Active", dose: "40 mg", route: "PO", frequency: "Nightly", prescriber: "Dr. Lin Chen", indication: "Hyperlipidemia" },
    ],
    allergies: [
      { allergen: "Penicillin", reaction: "Hives", severity: "Severe", type: "Allergy", verified: "2014-02-10" },
      { allergen: "Sulfamethoxazole (sulfa antibiotics)", reaction: "Rash", severity: "Moderate", type: "Allergy", verified: "2017-06-01" },
    ],
    vitals: [
      { date: "2026-09-21", bp: "138/84", hr: 88, weight: "71.2 kg", temp: "36.9 °C", rr: 20, spo2: 94, bmi: "24.6" },
      { date: "2026-09-20", bp: "158/92", hr: 98, weight: "72.0 kg", temp: "36.8 °C", rr: 24, spo2: 91, bmi: "24.9" },
      { date: "2026-08-24", bp: "146/88", hr: 82, weight: "68.9 kg", temp: "36.7 °C", rr: 16, spo2: 96, bmi: "23.8" },
      { date: "2026-05-18", bp: "140/86", hr: 78, weight: "68.4 kg", temp: "36.6 °C", rr: 16, spo2: 97, bmi: "23.6" },
    ],
    results: [
      { date: "2026-09-20", name: "BNP", value: "1480", unit: "pg/mL", range: "< 100", flag: "High", status: "Final", loinc: LOINC.bnp, orderedBy: "ED physician" },
      { date: "2026-09-20", name: "Potassium", value: "5.4", unit: "mmol/L", range: "3.5–5.1", flag: "High", status: "Final", loinc: LOINC.potassium, orderedBy: "ED physician" },
      { date: "2026-09-20", name: "Creatinine", value: "1.5", unit: "mg/dL", range: "0.74–1.35", flag: "High", status: "Final", loinc: LOINC.creatinine, orderedBy: "ED physician" },
      { date: "2026-09-20", name: "eGFR", value: "50", unit: "mL/min/1.73m²", range: "> 60", flag: "Low", status: "Final", loinc: LOINC.egfr, orderedBy: "ED physician" },
      { date: "2026-09-20", name: "Glucose", value: "212", unit: "mg/dL", range: "70–99", flag: "High", status: "Final", loinc: LOINC.glucose, orderedBy: "ED physician" },
      { date: "2026-08-24", name: "Hemoglobin A1c", value: "8.4", unit: "%", range: "4.0–5.6", flag: "High", status: "Final", loinc: LOINC.a1c, orderedBy: "Dr. Lin Chen" },
    ],
    encounters: [
      { id: "ENC-005-1", date: "2026-08-24", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Diabetes, CKD, HF follow-up", status: "Completed" },
      { id: "ENC-005-2", date: "2026-09-18", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Ankle swelling", status: "No-show" },
      { id: "ENC-005-3", date: "2026-09-20", type: "Inpatient", provider: "Dr. Ana Morales", department: "4 West Medical-Surgical", reason: "Acute on chronic systolic heart failure", status: "Active admission", location: "4 West · Rm 412-B" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-005A",
        author: "Dr. Ana Morales",
        recordedAt: "2026-09-20T21:15:00-04:00",
        encounterId: "ENC-005-3",
        source: "Typed",
        subjective: "Three days of worsening leg swelling and orthopnea (three pillows). Missed clinic visit 9/18. Ran out of furosemide last week.",
        objective: "BP 158/92, HR 98, RR 24, SpO2 91% RA → 95% on 2 L. JVP elevated, bibasilar crackles, 2+ pitting edema to mid-shin. BNP 1,480; K 5.4; creatinine 1.5 (baseline 1.3). Weight 72.0 kg (dry weight 68.5 kg).",
        assessment: "Acute on chronic systolic heart failure (EF 30% in 2025) precipitated by missed diuretic. CKD 3a with mild AKI. Hyperkalemia on lisinopril.",
        plan: "Furosemide 40 mg IV BID; strict I&O and daily weights. Hold lisinopril and metformin. Continue carvedilol, hydralazine. Fall precautions. Pharmacy medication reconciliation in the morning.",
      }),
    ],
  },
  {
    id: "PT-006",
    mrn: "6105105",
    name: "Priya Shah",
    dob: "1988-10-30",
    sex: "Female",
    pronouns: "she/her",
    language: "Gujarati",
    interpreterNeeded: true,
    address: "37-25 74th Street, Apt 4D, Jackson Heights, NY 11372",
    phone: "(212) 555-1105",
    insurance: "Crescent Commercial PPO (fictional)",
    insurerId: "INS-CPPO",
    memberId: "CPPO-48395",
    pcp: "Dr. Ravi Patel",
    careTeam: [{ name: "Dr. Ravi Patel", role: "PCP · Family medicine" }],
    flags: ["Interpreter: Gujarati", "Proxy on file"],
    problems: [
      { code: "E03.9", display: "Hypothyroidism, unspecified", onset: "2020-01-09", status: "Active" },
      { code: "N92.0", display: "Excessive and frequent menstruation with regular cycle", onset: "2026-04-02", status: "Active" },
    ],
    medications: [
      { name: "Levothyroxine 75 mcg tablet", sig: "1 tablet by mouth every morning on an empty stomach", status: "Active", dose: "75 mcg", route: "PO", frequency: "Daily", prescriber: "Dr. Ravi Patel", indication: "Hypothyroidism" },
    ],
    allergies: [{ allergen: "Latex", reaction: "Contact dermatitis", severity: "Mild", type: "Allergy", verified: "2021-03-15" }],
    vitals: [
      { date: "2026-08-03", bp: "116/72", hr: 70, weight: "148 lb", temp: "36.6 °C", rr: 14, spo2: 99, bmi: "25.4" },
      { date: "2026-04-02", bp: "118/74", hr: 74, weight: "150 lb", temp: "36.7 °C", rr: 14, spo2: 99, bmi: "25.7" },
      { date: "2025-10-20", bp: "114/70", hr: 68, weight: "147 lb", temp: "36.5 °C", rr: 14, spo2: 99, bmi: "25.2" },
    ],
    results: [
      { date: "2026-08-03", name: "TSH", value: "2.1", unit: "mIU/L", range: "0.4–4.0", flag: "", status: "Final", loinc: LOINC.tsh, orderedBy: "Dr. Ravi Patel" },
      { date: "2026-04-02", name: "Hemoglobin", value: "11.6", unit: "g/dL", range: "12.0–15.5", flag: "Low", status: "Final", loinc: LOINC.hgb, orderedBy: "Dr. Ravi Patel" },
    ],
    encounters: [
      { id: "ENC-006-1", date: "2026-04-02", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "Heavy periods", status: "Completed" },
      { id: "ENC-006-2", date: "2026-08-03", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "Thyroid follow-up", status: "Completed" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-006A",
        author: "Dr. Ravi Patel",
        recordedAt: "2026-08-03T17:40:00-04:00",
        encounterId: "ENC-006-2",
        source: "Typed",
        subjective: "Feels well on levothyroxine. Prefers evening visits (works days). Her mother attends visits and needs a Gujarati interpreter; the patient reads English but prefers Gujarati for clinical detail.",
        objective: "BP 116/72, HR 70. Thyroid non-tender, no nodules.",
        assessment: "Hypothyroidism, controlled (TSH 2.1).",
        plan: "Continue levothyroxine 75 mcg. Pelvic ultrasound referral for heavy periods. Schedule evening visit with interpreter.",
      }),
    ],
    proxyAccess: [{ name: "Anjali Shah", relationship: "Daughter", scope: "Scheduling and messages" }],
  },
  {
    id: "PT-007",
    mrn: "6105106",
    name: "Devon Brooks",
    dob: "2001-06-16",
    sex: "X",
    pronouns: "they/them",
    genderIdentity: "Nonbinary",
    sexAssignedAtBirth: "Female",
    legalNameOnCoverage: "Danielle Brooks",
    language: "English",
    address: "421 Tompkins Avenue, Apt 3, Brooklyn, NY 11216",
    phone: "(212) 555-1106",
    insurance: "NY Medicaid Managed Care (teaching plan)",
    insurerId: "INS-MMC",
    memberId: "MCD-48432",
    pcp: "Sam Brooks, NP",
    careTeam: [{ name: "Sam Brooks, NP", role: "PCP · Internal medicine" }],
    flags: ["Use name Devon · they/them"],
    problems: [
      { code: "F41.1", display: "Generalized anxiety disorder", onset: "2023-11-02", status: "Active" },
      { code: "J30.9", display: "Allergic rhinitis, unspecified", onset: "2018-04-20", status: "Active" },
    ],
    medications: [
      { name: "Sertraline 50 mg tablet", sig: "1 tablet by mouth once daily", status: "Active", dose: "50 mg", route: "PO", frequency: "Daily", prescriber: "Sam Brooks, NP", indication: "Anxiety" },
      { name: "Cetirizine 10 mg tablet", sig: "1 tablet by mouth daily as needed for allergies", status: "Active", dose: "10 mg", route: "PO", frequency: "Daily PRN", prescriber: "Sam Brooks, NP", indication: "Allergic rhinitis" },
    ],
    allergies: [{ allergen: "No known drug allergies", reaction: "", severity: "None", type: "Allergy", verified: "2026-03-30" }],
    vitals: [
      { date: "2026-03-30", bp: "114/70", hr: 72, weight: "139 lb", temp: "36.7 °C", rr: 14, spo2: 99, bmi: "22.4" },
      { date: "2025-09-15", bp: "116/72", hr: 76, weight: "137 lb", temp: "36.6 °C", rr: 14, spo2: 99, bmi: "22.1" },
      { date: "2025-03-11", bp: "112/68", hr: 70, weight: "136 lb", temp: "36.8 °C", rr: 14, spo2: 99, bmi: "21.9" },
    ],
    results: [
      { date: "2026-03-30", name: "TSH", value: "1.4", unit: "mIU/L", range: "0.4–4.0", flag: "", status: "Final", loinc: LOINC.tsh, orderedBy: "Sam Brooks, NP" },
    ],
    encounters: [
      { id: "ENC-007-1", date: "2026-03-30", type: "Office visit", provider: "Sam Brooks, NP", department: "Internal Medicine", reason: "Anxiety follow-up", status: "Completed" },
      { id: "ENC-007-2", date: "2026-09-21", type: "Office visit", provider: "Sam Brooks, NP", department: "Internal Medicine", reason: "Medication check", status: "Scheduled" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-007A",
        author: "Sam Brooks, NP",
        recordedAt: "2026-03-30T14:05:00-04:00",
        encounterId: "ENC-007-1",
        source: "Typed",
        subjective: "Devon (they/them) reports fewer panic episodes on sertraline. Asked that staff use their name, not the legal name on their insurance card; front desk called out the legal name in the waiting room last visit.",
        objective: "BP 114/70. GAD-7 score 7 (was 14).",
        assessment: "Generalized anxiety disorder, improving.",
        plan: "Continue sertraline 50 mg. Chosen name and pronouns updated in registration; ask HIM to confirm the schedule and wristband print chosen name. Return in 6 months.",
      }),
    ],
  },
  {
    id: "PT-008",
    mrn: "6105107",
    name: "Sofia Petrov",
    dob: "1947-12-09",
    sex: "Female",
    pronouns: "she/her",
    language: "Russian",
    interpreterNeeded: true,
    address: "2830 Ocean Parkway, Apt 9J, Brooklyn, NY 11235",
    phone: "(212) 555-1107",
    insurance: "Medicare Part A/B (teaching plan)",
    insurerId: "INS-MCR",
    memberId: "MCR-48469",
    pcp: "Dr. Lin Chen",
    careTeam: [
      { name: "Dr. Ana Morales", role: "Attending hospitalist" },
      { name: "Nina Alvarez, RN", role: "Night nurse, 4 West" },
      { name: "Jordan Park, RN", role: "Charge nurse, 4 West" },
      { name: "Irina Petrova", role: "Daughter · health care proxy" },
    ],
    codeStatus: "DNR/DNI (MOLST on file)",
    location: "4 West · Rm 415-A",
    admittedAt: "2026-09-19T14:10:00-04:00",
    weightKg: 58,
    flags: ["Fall risk", "Interpreter: Russian", "Anticoagulated"],
    problems: [
      { code: "J18.9", display: "Pneumonia, unspecified organism", onset: "2026-09-19", status: "Active" },
      { code: "I48.91", display: "Unspecified atrial fibrillation", onset: "2018-02-11", status: "Active" },
      { code: "I10", display: "Essential (primary) hypertension", onset: "2009-06-30", status: "Active" },
      { code: "M81.0", display: "Age-related osteoporosis without current pathological fracture", onset: "2016-09-01", status: "Active" },
    ],
    medications: [
      { name: "Metoprolol tartrate 25 mg tablet", sig: "1 tablet by mouth twice daily; hold for HR < 55 or SBP < 100", status: "Active", dose: "25 mg", route: "PO", frequency: "BID", prescriber: "Dr. Lin Chen", indication: "Atrial fibrillation rate control" },
      { name: "Apixaban 5 mg tablet", sig: "1 tablet by mouth twice daily", status: "Active", dose: "5 mg", route: "PO", frequency: "BID", prescriber: "Dr. Lin Chen", indication: "Stroke prevention in AF" },
      { name: "Amlodipine 5 mg tablet", sig: "1 tablet by mouth once daily (held inpatient)", status: "On hold", dose: "5 mg", route: "PO", frequency: "Daily", prescriber: "Dr. Lin Chen", indication: "Hypertension" },
      { name: "Alendronate 70 mg tablet", sig: "1 tablet by mouth weekly on Sunday morning", status: "Active", dose: "70 mg", route: "PO", frequency: "Weekly", prescriber: "Dr. Lin Chen", indication: "Osteoporosis" },
    ],
    allergies: [
      { allergen: "Sulfamethoxazole (sulfa antibiotics)", reaction: "Rash", severity: "Moderate", type: "Allergy", verified: "2011-05-06" },
      { allergen: "Codeine", reaction: "Nausea and vomiting", severity: "Mild", type: "Intolerance", verified: "2016-09-01" },
    ],
    vitals: [
      { date: "2026-09-21", bp: "118/66", hr: 96, weight: "58 kg", temp: "38.0 °C", rr: 21, spo2: 95, bmi: "22.7" },
      { date: "2026-09-19", bp: "132/80", hr: 104, weight: "58.4 kg", temp: "38.4 °C", rr: 22, spo2: 93, bmi: "22.8" },
      { date: "2026-07-12", bp: "128/74", hr: 70, weight: "59 kg", temp: "36.6 °C", rr: 16, spo2: 97, bmi: "23.0" },
    ],
    results: [
      { date: "2026-09-21", name: "White blood cell count", value: "15.8", unit: "×10³/µL", range: "4.0–11.0", flag: "High", status: "Final", loinc: LOINC.wbc, orderedBy: "Dr. Ana Morales" },
      { date: "2026-09-19", name: "White blood cell count", value: "14.2", unit: "×10³/µL", range: "4.0–11.0", flag: "High", status: "Final", loinc: LOINC.wbc, orderedBy: "ED physician" },
      { date: "2026-09-19", name: "Procalcitonin", value: "0.9", unit: "ng/mL", range: "< 0.25", flag: "High", status: "Final", loinc: LOINC.procalcitonin, orderedBy: "ED physician" },
      { date: "2026-09-19", name: "Lactate", value: "1.8", unit: "mmol/L", range: "0.5–2.0", flag: "", status: "Final", loinc: LOINC.lactate, orderedBy: "ED physician" },
      { date: "2026-09-19", name: "Sodium", value: "133", unit: "mmol/L", range: "135–145", flag: "Low", status: "Final", loinc: LOINC.sodium, orderedBy: "ED physician" },
      // Ordered as an add-on but never resulted: the missingness example for Query Studio.
      { date: "2026-09-19", name: "Hemoglobin A1c", value: "", unit: "%", range: "4.0–5.6", flag: "", status: "Pending", loinc: LOINC.a1c, orderedBy: "Dr. Ana Morales" },
    ],
    encounters: [
      { id: "ENC-008-1", date: "2026-07-12", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "AF and hypertension follow-up", status: "Completed" },
      { id: "ENC-008-2", date: "2026-09-19", type: "Inpatient", provider: "Dr. Ana Morales", department: "4 West Medical-Surgical", reason: "Community-acquired pneumonia", status: "Active admission", location: "4 West · Rm 415-A" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-008A",
        author: "Dr. Ana Morales",
        recordedAt: "2026-09-21T07:50:00-04:00",
        encounterId: "ENC-008-2",
        source: "Typed",
        subjective: "Hospital day 3. Cough productive, less short of breath yesterday; overnight nurse reports low-grade fevers and poor intake. Russian interpreter (phone) used; daughter Irina at bedside.",
        objective: "T 38.0, HR 96, BP 118/66, RR 21, SpO2 95% RA. Right lower lobe crackles. WBC 15.8 (from 14.2).",
        assessment: "Community-acquired pneumonia, right lower lobe, not yet improving. AF, rate acceptable.",
        plan: "Continue ceftriaxone and azithromycin. Nursing: vitals every 4 h and early warning score; call for EWS ≥ 5. Repeat lactate if febrile or hypotensive. Metoprolol 25 mg BID with hold parameters.",
      }),
    ],
  },
  {
    id: "PT-009",
    mrn: "6105108",
    name: "Mateo Rivera",
    dob: "2012-04-04",
    sex: "Male",
    pronouns: "he/him",
    language: "Spanish",
    address: "1575 Watson Avenue, Bronx, NY 10472",
    phone: "(212) 555-1108",
    insurance: "NY Medicaid Managed Care (teaching plan)",
    insurerId: "INS-MMC",
    memberId: "CHP-48506",
    pcp: "Dr. Ravi Patel",
    careTeam: [
      { name: "Dr. Ravi Patel", role: "PCP · Family medicine" },
      { name: "Carmen Rivera", role: "Parent · portal proxy" },
    ],
    flags: ["Minor · proxy on file", "Confidential adolescent note", "Peanut allergy"],
    problems: [
      { code: "J45.30", display: "Mild persistent asthma, uncomplicated", onset: "2019-10-03", status: "Active" },
      { code: "Z91.010", display: "Allergy to peanuts", onset: "2015-06-22", status: "Active" },
    ],
    medications: [
      { name: "Fluticasone HFA 44 mcg/actuation inhaler", sig: "2 puffs twice daily with spacer; rinse mouth after use", status: "Active", dose: "88 mcg", route: "Inhaled", frequency: "BID", prescriber: "Dr. Ravi Patel", indication: "Asthma control" },
      { name: "Albuterol HFA 90 mcg/actuation inhaler", sig: "2 puffs every 4 hours as needed for wheeze", status: "Active", dose: "180 mcg", route: "Inhaled", frequency: "Every 4 h PRN", prescriber: "Dr. Ravi Patel", indication: "Asthma rescue" },
      { name: "Epinephrine 0.3 mg auto-injector", sig: "Inject into outer thigh for anaphylaxis; call 911", status: "Active", dose: "0.3 mg", route: "IM", frequency: "Once PRN", prescriber: "Dr. Ravi Patel", indication: "Peanut allergy" },
    ],
    allergies: [
      { allergen: "Peanut", reaction: "Anaphylaxis", severity: "Severe", type: "Allergy", verified: "2015-06-22" },
    ],
    vitals: [
      { date: "2026-09-10", bp: "108/64", hr: 82, weight: "103 lb", temp: "36.8 °C", rr: 18, spo2: 98, bmi: "19.1" },
      { date: "2026-02-03", bp: "104/62", hr: 86, weight: "97 lb", temp: "37.0 °C", rr: 20, spo2: 97, bmi: "18.7" },
      { date: "2025-09-08", bp: "102/60", hr: 84, weight: "92 lb", temp: "36.7 °C", rr: 18, spo2: 98, bmi: "18.4" },
    ],
    results: [],
    encounters: [
      { id: "ENC-009-1", date: "2026-02-03", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "Asthma flare", status: "Completed" },
      { id: "ENC-009-2", date: "2026-09-10", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "Annual well visit (age 14)", status: "Completed" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-009A",
        author: "Dr. Ravi Patel",
        recordedAt: "2026-09-10T16:20:00-04:00",
        encounterId: "ENC-009-2",
        source: "Typed",
        subjective: "Annual visit with mother (Carmen, Spanish). Asthma controlled; albuterol twice a month. Plays soccer.",
        objective: "Growth normal. Lungs clear. BP 108/64.",
        assessment: "Well adolescent. Mild persistent asthma, controlled. Peanut allergy.",
        plan: "Continue fluticasone. School asthma action plan and epinephrine form completed. Influenza vaccine today. HPV dose 2 due in 6 months.",
      }),
      note({
        id: "NOTE-SEED-009B",
        author: "Dr. Ravi Patel",
        recordedAt: "2026-09-10T16:35:00-04:00",
        encounterId: "ENC-009-2",
        source: "Typed",
        confidential: true,
        subjective: "CONFIDENTIAL ADOLESCENT SECTION (seen alone). Reports low mood since school started; PHQ-A score 11. Denies self-harm. Asked that his mother not be told yet.",
        objective: "Calm, good eye contact. No safety concerns on screening.",
        assessment: "Moderate depressive symptoms (PHQ-A 11); no current safety risk.",
        plan: "School counselor referral. Follow up alone in 2 weeks. Not for release to proxy under adolescent confidentiality rules.",
      }),
    ],
    proxyAccess: [{ name: "Carmen Rivera", relationship: "Parent", scope: "Full portal access (minor)" }],
  },
  {
    id: "PT-010",
    mrn: "6105109",
    name: "Grace Kim",
    dob: "1970-09-21",
    sex: "Female",
    pronouns: "she/her",
    language: "Korean",
    address: "150-12 Northern Boulevard, Apt 5A, Flushing, NY 11354",
    phone: "(212) 555-1109",
    insurance: "Crescent Commercial HMO (fictional)",
    insurerId: "INS-CHMO",
    memberId: "CHMO-48543",
    pcp: "Dr. Lin Chen",
    careTeam: [
      { name: "Dr. Lin Chen", role: "PCP · Internal medicine" },
      { name: "Dr. Amara Osei", role: "Endocrinology" },
    ],
    flags: ["Birthday today"],
    problems: [
      { code: "E11.65", display: "Type 2 diabetes mellitus with hyperglycemia", onset: "2019-05-14", status: "Active" },
      { code: "E78.5", display: "Hyperlipidemia, unspecified", onset: "2019-05-14", status: "Active" },
    ],
    medications: [
      { name: "Metformin 1,000 mg tablet", sig: "1 tablet by mouth twice daily with meals", status: "Active", dose: "1,000 mg", route: "PO", frequency: "BID", prescriber: "Dr. Lin Chen", indication: "Type 2 diabetes" },
      { name: "Atorvastatin 40 mg tablet", sig: "1 tablet by mouth at bedtime", status: "Active", dose: "40 mg", route: "PO", frequency: "Nightly", prescriber: "Dr. Lin Chen", indication: "Hyperlipidemia" },
    ],
    allergies: [{ allergen: "No known drug allergies", reaction: "", severity: "None", type: "Allergy", verified: "2026-09-08" }],
    vitals: [
      { date: "2026-09-16", bp: "134/82", hr: 78, weight: "152 lb", temp: "36.7 °C", rr: 16, spo2: 98, bmi: "27.0" },
      { date: "2026-09-08", bp: "136/80", hr: 80, weight: "153 lb", temp: "36.6 °C", rr: 16, spo2: 98, bmi: "27.1" },
      { date: "2026-03-02", bp: "132/78", hr: 76, weight: "150 lb", temp: "36.8 °C", rr: 14, spo2: 99, bmi: "26.6" },
    ],
    results: [
      { date: "2026-09-08", name: "Hemoglobin A1c", value: "9.1", unit: "%", range: "4.0–5.6", flag: "High", status: "Final", loinc: LOINC.a1c, orderedBy: "Dr. Lin Chen" },
      { date: "2026-09-08", name: "LDL cholesterol", value: "118", unit: "mg/dL", range: "< 100", flag: "High", status: "Final", loinc: LOINC.ldl, orderedBy: "Dr. Lin Chen" },
      { date: "2026-03-02", name: "Hemoglobin A1c", value: "8.6", unit: "%", range: "4.0–5.6", flag: "High", status: "Final", loinc: LOINC.a1c, orderedBy: "Dr. Lin Chen" },
    ],
    encounters: [
      { id: "ENC-010-1", date: "2026-09-08", type: "Office visit", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Diabetes follow-up; endocrinology referral", status: "Completed" },
      { id: "ENC-010-2", date: "2026-09-16", type: "Office visit", provider: "Dr. Amara Osei", department: "Endocrinology", reason: "New consult: uncontrolled diabetes", status: "Completed" },
      { id: "ENC-010-3", date: "2026-09-21", type: "Telehealth", provider: "Dr. Lin Chen", department: "Internal Medicine", reason: "Medication review", status: "Scheduled" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-010A",
        author: "Dr. Amara Osei",
        recordedAt: "2026-09-16T13:15:00-04:00",
        encounterId: "ENC-010-2",
        source: "Typed",
        subjective: "Referred by Dr. Chen for A1c 9.1% on metformin. Korean interpreter declined; patient prefers English with her son present.",
        objective: "BP 134/82, BMI 27.0. Monofilament intact.",
        assessment: "Type 2 diabetes with hyperglycemia, above goal on metformin monotherapy.",
        plan: "Add a GLP-1 receptor agonist after insurance review; diabetes self-management education; return in 3 months.",
      }),
    ],
  },
  {
    id: "PT-011",
    mrn: "6105110",
    name: "Noah Williams",
    dob: "1981-02-12",
    sex: "Male",
    pronouns: "he/him",
    language: "English",
    address: "310 East 70th Street, Apt 12A, New York, NY 10021",
    phone: "(212) 555-1110",
    insurance: "Crescent Commercial PPO (fictional)",
    insurerId: "INS-CPPO",
    memberId: "CPPO-48580",
    pcp: "Dr. Lin Chen",
    careTeam: [
      { name: "Dr. Lin Chen", role: "PCP · Internal medicine (supervising)" },
      { name: "Sam Brooks, NP", role: "Nurse practitioner" },
    ],
    flags: [],
    problems: [
      { code: "E78.5", display: "Hyperlipidemia, unspecified", onset: "2022-03-10", status: "Active" },
      { code: "R73.03", display: "Prediabetes", onset: "2024-09-02", status: "Active" },
      { code: "H61.21", display: "Impacted cerumen, right ear", onset: "2026-09-15", status: "Resolved" },
    ],
    medications: [
      { name: "Atorvastatin 10 mg tablet", sig: "1 tablet by mouth at bedtime", status: "Active", dose: "10 mg", route: "PO", frequency: "Nightly", prescriber: "Dr. Lin Chen", indication: "Hyperlipidemia" },
    ],
    allergies: [{ allergen: "No known drug allergies", reaction: "", severity: "None", type: "Allergy", verified: "2026-09-15" }],
    vitals: [
      { date: "2026-09-15", bp: "138/86", hr: 74, weight: "201 lb", temp: "36.7 °C", rr: 14, spo2: 98, bmi: "29.7" },
      { date: "2026-03-18", bp: "134/84", hr: 72, weight: "198 lb", temp: "36.6 °C", rr: 14, spo2: 99, bmi: "29.2" },
      { date: "2025-09-22", bp: "130/82", hr: 70, weight: "196 lb", temp: "36.8 °C", rr: 14, spo2: 99, bmi: "28.9" },
    ],
    results: [
      { date: "2026-09-10", name: "LDL cholesterol", value: "142", unit: "mg/dL", range: "< 100", flag: "High", status: "Final", loinc: LOINC.ldl, orderedBy: "Dr. Ravi Patel" },
      { date: "2026-09-10", name: "Hemoglobin A1c", value: "6.1", unit: "%", range: "4.0–5.6", flag: "High", status: "Final", loinc: LOINC.a1c, orderedBy: "Dr. Ravi Patel" },
    ],
    encounters: [
      { id: "ENC-011-1", date: "2026-09-10", type: "Nurse visit", provider: "Fordham Health Lab", department: "Laboratory", reason: "Fasting labs (ordered by Dr. Patel, covering)", status: "Completed" },
      { id: "ENC-011-2", date: "2026-09-15", type: "Office visit", provider: "Sam Brooks, NP", department: "Internal Medicine", reason: "Ear fullness; blood pressure", status: "Completed" },
      { id: "ENC-011-3", date: "2026-09-21", type: "Office visit", provider: "Dr. Ravi Patel", department: "Family Medicine", reason: "Lipid follow-up", status: "Scheduled" },
    ],
    notes: [
      note({
        id: "NOTE-SEED-011A",
        author: "Sam Brooks, NP",
        recordedAt: "2026-09-15T10:55:00-04:00",
        encounterId: "ENC-011-2",
        source: "Typed",
        cosignRequestedFrom: "Dr. Chen",
        subjective: "Right ear fullness and muffled hearing for one week. No pain or discharge.",
        objective: "Right canal occluded with impacted cerumen; removed with curette under direct visualization; TM intact afterward. BP 138/86.",
        assessment: "Impacted cerumen, right ear, removed. Elevated blood pressure reading without diagnosis of hypertension.",
        plan: "Home BP log for two weeks; recheck at lipid visit 9/21. Co-signature requested from Dr. Chen (supervising physician).",
      }),
    ],
  },
  {
    id: "PT-012",
    mrn: "6105111",
    name: "Liu H.",
    dob: "1984-03-19",
    sex: "Female",
    pronouns: "she/her",
    language: "Mandarin",
    interpreterNeeded: true,
    address: "120 Example Ave Apt 4B, New York, NY 10000",
    phone: "(917) 555-4812",
    insurance: "Crescent Commercial PPO (fictional)",
    insurerId: "INS-CPPO",
    memberId: "CPPO-48617",
    flags: ["Quick registration · unverified"],
    careTeam: [],
    problems: [],
    medications: [],
    allergies: [{ allergen: "Not yet reviewed", reaction: "", severity: "Unknown" }],
    vitals: [],
    results: [],
    encounters: [
      { id: "ENC-012-1", date: "2026-09-15", type: "Office visit", provider: "Physical therapy scheduling", department: "Rehabilitation", reason: "Created by phone quick-registration for a PT referral", status: "Scheduled" },
    ],
    notes: [],
    // Created 2026-09-15 by phone quick-registration (see ENC-012-1). Do not set registeredAt:
    // that field marks learner-registered records, which an A1 scoped reset removes.
    duplicateCandidate: "PT-001",
  },
];
