-- Authenticated HINF 6105 workspace, assignment progress, submissions, and grading.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS ehr_course_users (
  email TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  image TEXT,
  role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'instructor', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ehr_user_workspaces (
  email TEXT PRIMARY KEY REFERENCES ehr_course_users(email) ON DELETE CASCADE,
  workspace JSONB NOT NULL,
  schema_version INT NOT NULL DEFAULT 2,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ehr_assignment_progress (
  email TEXT NOT NULL REFERENCES ehr_course_users(email) ON DELETE CASCADE,
  assignment_id TEXT NOT NULL,
  progress JSONB NOT NULL DEFAULT '{}'::jsonb,
  percent_complete INT NOT NULL DEFAULT 0 CHECK (percent_complete BETWEEN 0 AND 100),
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (email, assignment_id)
);

CREATE TABLE IF NOT EXISTS ehr_activity_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL REFERENCES ehr_course_users(email) ON DELETE CASCADE,
  event_id TEXT NOT NULL,
  action TEXT NOT NULL,
  patient_id TEXT,
  detail TEXT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (email, event_id)
);

CREATE TABLE IF NOT EXISTS ehr_assignment_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL REFERENCES ehr_course_users(email) ON DELETE CASCADE,
  assignment_id TEXT NOT NULL,
  reflection TEXT NOT NULL,
  evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'graded', 'returned')),
  version INT NOT NULL DEFAULT 1,
  score NUMERIC(5,2) CHECK (score IS NULL OR (score >= 0 AND score <= 100)),
  feedback TEXT,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  graded_at TIMESTAMPTZ,
  graded_by TEXT,
  UNIQUE (email, assignment_id)
);

CREATE INDEX IF NOT EXISTS idx_ehr_activity_email_time ON ehr_activity_events(email, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_ehr_activity_action ON ehr_activity_events(action);
CREATE INDEX IF NOT EXISTS idx_ehr_progress_assignment ON ehr_assignment_progress(assignment_id, percent_complete);
CREATE INDEX IF NOT EXISTS idx_ehr_submissions_assignment ON ehr_assignment_submissions(assignment_id, status, submitted_at DESC);

ALTER TABLE ehr_course_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_user_workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_assignment_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_activity_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_assignment_submissions ENABLE ROW LEVEL SECURITY;

-- These tables are accessed only through authenticated Next.js route handlers
-- using the service role. No direct browser policies are intentionally created.

INSERT INTO ehr_course_users (email, name, role)
VALUES ('msanfilippo4@fordham.edu', 'Michael Sanfilippo', 'instructor')
ON CONFLICT (email) DO UPDATE SET role = 'instructor', name = EXCLUDED.name;
