-- FordMS course operations: admin configuration, submission history, rubric grading,
-- scoped resets, provenance, releases, and rate limiting.
-- Additive and idempotent. Safe to re-run. Rollback: 009_fordms_course_ops_down.sql

-- ---------------------------------------------------------------------------
-- Column additions to existing tables
-- ---------------------------------------------------------------------------
ALTER TABLE ehr_course_users
  ADD COLUMN IF NOT EXISTS enrollment_status TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS first_name TEXT,
  ADD COLUMN IF NOT EXISTS last_name TEXT,
  ADD COLUMN IF NOT EXISTS blackboard_username TEXT,
  ADD COLUMN IF NOT EXISTS section TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ehr_course_users_enrollment_status_check') THEN
    ALTER TABLE ehr_course_users ADD CONSTRAINT ehr_course_users_enrollment_status_check
      CHECK (enrollment_status IN ('invited', 'active', 'dropped', 'test'));
  END IF;
END $$;

ALTER TABLE ehr_activity_events
  ADD COLUMN IF NOT EXISTS provenance TEXT NOT NULL DEFAULT 'earned',
  ADD COLUMN IF NOT EXISTS context TEXT,
  ADD COLUMN IF NOT EXISTS actor_role TEXT;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ehr_activity_events_provenance_check') THEN
    ALTER TABLE ehr_activity_events ADD CONSTRAINT ehr_activity_events_provenance_check
      CHECK (provenance IN ('earned', 'imported'));
  END IF;
END $$;

ALTER TABLE ehr_assignment_progress
  ADD COLUMN IF NOT EXISTS earned_units INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS imported_units INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_units INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS computed_from TEXT NOT NULL DEFAULT 'client',
  ADD COLUMN IF NOT EXISTS config_version INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'not_started';

ALTER TABLE ehr_assignment_submissions
  ADD COLUMN IF NOT EXISTS current_version_id UUID,
  ADD COLUMN IF NOT EXISTS config_version INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rubric_total NUMERIC(6,2),
  ADD COLUMN IF NOT EXISTS returned_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS returned_by TEXT,
  ADD COLUMN IF NOT EXISTS return_comment TEXT,
  ADD COLUMN IF NOT EXISTS late BOOLEAN NOT NULL DEFAULT false;

-- Widen the submission status CHECK to include revision_requested.
DO $$
DECLARE
  existing TEXT;
BEGIN
  SELECT conname INTO existing FROM pg_constraint
   WHERE conrelid = 'ehr_assignment_submissions'::regclass AND contype = 'c'
     AND pg_get_constraintdef(oid) LIKE '%status%';
  IF existing IS NOT NULL AND pg_get_constraintdef((SELECT oid FROM pg_constraint WHERE conname = existing)) NOT LIKE '%revision_requested%' THEN
    EXECUTE format('ALTER TABLE ehr_assignment_submissions DROP CONSTRAINT %I', existing);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'ehr_assignment_submissions'::regclass AND contype = 'c' AND pg_get_constraintdef(oid) LIKE '%revision_requested%') THEN
    ALTER TABLE ehr_assignment_submissions ADD CONSTRAINT ehr_assignment_submissions_status_check
      CHECK (status IN ('submitted', 'graded', 'returned', 'revision_requested'));
  END IF;
END $$;

ALTER TABLE ehr_user_workspaces
  ADD COLUMN IF NOT EXISTS last_import_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_reset_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reset_markers JSONB NOT NULL DEFAULT '{}'::jsonb;

-- ---------------------------------------------------------------------------
-- New tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ehr_config_versions (
  version INT PRIMARY KEY,
  status TEXT NOT NULL CHECK (status IN ('draft', 'published', 'archived')),
  config JSONB NOT NULL,
  change_summary TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_by TEXT,
  published_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ehr_config_published ON ehr_config_versions ((status)) WHERE status = 'published';

CREATE TABLE IF NOT EXISTS ehr_admin_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor TEXT NOT NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT,
  detail JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ehr_admin_events_time ON ehr_admin_events (created_at DESC);

CREATE TABLE IF NOT EXISTS ehr_assignment_releases (
  assignment_id TEXT PRIMARY KEY,
  state TEXT NOT NULL DEFAULT 'released' CHECK (state IN ('hidden', 'released', 'closed')),
  release_at TIMESTAMPTZ,
  due_at TIMESTAMPTZ,
  close_at TIMESTAMPTZ,
  accept_late BOOLEAN NOT NULL DEFAULT true,
  updated_by TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ehr_submission_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id UUID NOT NULL REFERENCES ehr_assignment_submissions (id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  assignment_id TEXT NOT NULL,
  version INT NOT NULL,
  reflection TEXT NOT NULL,
  evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
  progress_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  config_version INT NOT NULL DEFAULT 0,
  workspace_sha256 TEXT,
  late BOOLEAN NOT NULL DEFAULT false,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (email, assignment_id, version)
);
CREATE INDEX IF NOT EXISTS idx_ehr_subversions_email ON ehr_submission_versions (email, assignment_id, version DESC);

CREATE OR REPLACE FUNCTION ehr_submission_versions_immutable() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'ehr_submission_versions rows are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ehr_submission_versions_immutable ON ehr_submission_versions;
CREATE TRIGGER trg_ehr_submission_versions_immutable
  BEFORE UPDATE ON ehr_submission_versions
  FOR EACH ROW EXECUTE FUNCTION ehr_submission_versions_immutable();

CREATE TABLE IF NOT EXISTS ehr_rubric_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id UUID NOT NULL REFERENCES ehr_assignment_submissions (id) ON DELETE CASCADE,
  version INT NOT NULL,
  criterion_index INT NOT NULL,
  criterion TEXT NOT NULL,
  points_possible NUMERIC(6,2) NOT NULL,
  points_awarded NUMERIC(6,2) NOT NULL CHECK (points_awarded >= 0),
  comment TEXT,
  graded_by TEXT NOT NULL,
  graded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (submission_id, version, criterion_index)
);

CREATE TABLE IF NOT EXISTS ehr_grade_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id UUID NOT NULL REFERENCES ehr_assignment_submissions (id) ON DELETE CASCADE,
  version INT NOT NULL,
  email TEXT NOT NULL,
  assignment_id TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('graded', 'regraded', 'returned', 'comment', 'reopened', 'submitted')),
  actor TEXT NOT NULL,
  score NUMERIC(6,2),
  rubric JSONB,
  feedback TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ehr_grade_events_sub ON ehr_grade_events (submission_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ehr_workspace_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL REFERENCES ehr_course_users (email) ON DELETE CASCADE,
  reason TEXT NOT NULL CHECK (reason IN ('scoped_reset', 'full_reset', 'instructor_reset', 'import', 'pre_submit')),
  assignment_id TEXT,
  workspace JSONB NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ehr_snapshots_email ON ehr_workspace_snapshots (email, created_at DESC);

CREATE TABLE IF NOT EXISTS ehr_rate_limits (
  bucket TEXT PRIMARY KEY,
  window_start TIMESTAMPTZ NOT NULL,
  hits INT NOT NULL DEFAULT 0
);

CREATE OR REPLACE FUNCTION ehr_rate_limit_hit(p_bucket TEXT, p_limit INT, p_window_seconds INT) RETURNS BOOLEAN AS $$
DECLARE
  current_hits INT;
BEGIN
  INSERT INTO ehr_rate_limits (bucket, window_start, hits)
  VALUES (p_bucket, now(), 1)
  ON CONFLICT (bucket) DO UPDATE SET
    hits = CASE WHEN ehr_rate_limits.window_start < now() - make_interval(secs => p_window_seconds) THEN 1 ELSE ehr_rate_limits.hits + 1 END,
    window_start = CASE WHEN ehr_rate_limits.window_start < now() - make_interval(secs => p_window_seconds) THEN now() ELSE ehr_rate_limits.window_start END
  RETURNING hits INTO current_hits;
  RETURN current_hits <= p_limit;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Indexes on existing tables
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_ehr_activity_email_action_ctx ON ehr_activity_events (email, action, context);
CREATE INDEX IF NOT EXISTS idx_ehr_activity_provenance ON ehr_activity_events (email, provenance);

-- ---------------------------------------------------------------------------
-- Row-level security: enabled, no browser policies (service role only)
-- ---------------------------------------------------------------------------
ALTER TABLE ehr_config_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_admin_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_assignment_releases ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_submission_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_rubric_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_grade_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_workspace_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE ehr_rate_limits ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Backfill
-- ---------------------------------------------------------------------------
INSERT INTO ehr_assignment_releases (assignment_id, state, due_at, accept_late, updated_by) VALUES
  ('FORDMS-A1', 'released', '2026-10-11 23:59:00-04', true, 'migration-009'),
  ('FORDMS-A2', 'released', '2026-11-01 23:59:00-05', true, 'migration-009'),
  ('FORDMS-A3', 'released', '2026-11-22 23:59:00-05', true, 'migration-009'),
  ('FORDMS-A4', 'released', '2026-12-06 23:59:00-05', true, 'migration-009')
ON CONFLICT (assignment_id) DO NOTHING;

UPDATE ehr_course_users SET role = 'admin' WHERE email = 'msanfilippo4@fordham.edu' AND role = 'instructor';

INSERT INTO ehr_admin_events (actor, action, target_type, target_id, detail)
SELECT 'migration-009', 'migration_applied', 'schema', '009', '{"note":"Course operations schema applied; progress will be recomputed server-side on next sync."}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM ehr_admin_events WHERE action = 'migration_applied' AND target_id = '009');
